version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: todoapp-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: todoappdb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: dev123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: